### ISSUE TITLE
thanks for the credits <3

### ISSUE THREAD

**Issue by Pr0mises** [Nairdaa/jhud#1]
thanks nairdo for using my code love ya
if you rly want to credit ppl try them:

>promises: for the worse code of the world
>alkatrazbhop: the one and only who knows how the engine works and was able to calculate the gain.
>zedii: telling promises what speed per jump he used for what color and the great idea about jhud
>nairdo: for changing things

**Comment by Pr0mises** [comment]
ah ye and for proof: 
https://github.com/Pr0mises/jhud/ 
careful:
don't choke but wait you've already seen my code on here :)
P.S. check the prs

**Comment by Nairdaa** [comment]
That's not your code. You stole it and signed with your name and hence the description aka 

>define PLUGIN_AUTHOR "⌐■_■ fuck knows, code was stolen from 5 ppl and all of them claim the ownership. Deshitified, improved and fixed by Nairda."



I haven't signed it with my name. Zedii is a known copypasta "coder", thief. I deshitified (not completely) the plugin and added some stuff. If you have a personal issue with me, feel free to contact me in person instead of flinging shit here. 

Thanks in advance,
Nairda
